name: Build & test

on:
    push:
        branches: [ "main", "feature/v1" ]
    pull_request:
        branches: [ "main", "feature/v1" ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '10.0.x'

        - name: Restore packages
          run: dotnet restore src/Aggregates.slnx

        - name: Build
          run: dotnet build --no-restore src/Aggregates.slnx

        - name: Test
          run: dotnet test --no-build --verbosity normal src/Aggregates.slnx
