name: Publish package

on:
    workflow_run:
        workflows: ["Build & test"]
        branches: [ "main" ]
        types:
        - completed

jobs:
    publish:

        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
        - uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '10.0.x'

        - name: Restore packages
          run: dotnet restore src/Aggregates.slnx

        - name: Pack
          run: >
            dotnet pack
            -p:PackageId="${{ vars.NUGET_PACKAGE_ID }}"
            -p:Description="${{ vars.NUGET_DESCRIPTION }}"
            -p:Authors="${{ vars.NUGET_AUTHORS }}"
            -p:Copyright="${{ vars.NUGET_COPYRIGHT }}"
            -p:PackageProjectUrl="${{ vars.NUGET_PROJECT_URL }}"
            -c Release
            --no-restore
            src/Aggregates/

        - name: Push
          run: >
            dotnet nuget push
            src/Aggregates/bin/Release/Aggregates.*.nupkg
            -k ${{ secrets.NUGET_API_KEY }}
            -s ${{ vars.NUGET_PUSH_SOURCE }}
            --skip-duplicate
