name: Publish package

on:
    workflow_run:
        workflows: ["Build & test"]
        branches: [ "main" ]
        types:
        - completed

jobs:
    publish:

        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
        - uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '10.0.x'

        - name: Restore packages
          run: dotnet restore src/Aggregates.slnx

        - name: Pack
          run: dotnet pack src/Aggregates.slnx -c Release --no-restore --output packages/

        - name: Push
          run: >
            dotnet nuget push "packages/*.nupkg"
            -k ${{ secrets.NUGET_API_KEY }}
            -s ${{ vars.NUGET_PUSH_SOURCE }}
            --skip-duplicate
